# Generated by Django 5.2.1 on 2025-05-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда был создан этот код'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.UUIDField(db_index=True, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, связанный с этим кодом подтверждения Email'),
        ),
    ]
